name: Spin-Gui
version: 0.1.3
api-version: 1.16
main: me.HKS.HNS.Spin.Main
author: HNS_HKS
commands:
        Spin:
            description: If you spin you spin
permissions:
  spin.settings:
    description: To open the settings GUI
    default: op
  spin.config:
    description: To save and load the config
    default: op
  spin.help:
    description: To schow the help
    default: op
  spin.reset:
    description: To reset the spin time for the player
    default: op